### ISSUE TITLE
migrate-db doesn't seem to work locally

### ISSUE THREAD

**Issue by devinsodhi** [jlengstorf/roots.code.lengstorf.com#1]
i ran into some interesting errors trying to get it to work on my local server.wp-auth-check.js?ver=4.7 is one error, and another one was " wpsdb_max_request is not defined" in the tools.php for the plugin.

The rest is awesome. thanks

**Comment by jlengstorf** [comment]
Hey, @DevinSodhi, I've never seen those errors. It might make more sense to add this to the [WP Sync DB](https://github.com/wp-sync-db/wp-sync-db) repo as an issue.

I'm going to close this, but feel free to tag me in the other issue if you think I can help somehow.
