### ISSUE TITLE
wp db sync issue when syncing from prod to dev (local vagrant)

### ISSUE THREAD

**Issue by 7hr1LL** [jlengstorf/roots.code.lengstorf.com#3]
> WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-' at line 1]

I followed your amazing guide and everything worked fine, except when I tried to push from prod to local dev with wp db sync. Local => dev is working without any problems.

Its already mentioned here, but no one seems to have a workaround:
https://github.com/wp-sync-db/wp-sync-db/issues/48

Is anybody else having this issue? 

Thanks a lot in advance!

Best regards,
ThriLL

**Comment by jlengstorf** [comment]
Sorry for the delayed response here — this one slipped by me. If you're having issues and still need help, there's a [paid version of the plugin](https://deliciousbrains.com/wp-migrate-db-pro/) that includes support.

Good luck!
