### ISSUE TITLE
Part I: Install Trellis, start/projects location and folder names...

### ISSUE THREAD

**Issue by v3nt** [jlengstorf/roots.code.lengstorf.com#4]
He - great article!

I'm struggling with Trellis as a whole and think it might be with the very first few steps.
```

> # Move into the directory where where you keep dev projects.
> cd ~/dev/code.lengstorf.com/projects/

```

1. What folder should i be in to start with?
2. Why is `~/dev/code.lengstorf.com/` in a domain format? ie does it need to be or is ij just how you name folders?
3. Will all of your web projects (even for different clients) go into this folder?
  3b.  so my local projects will be in ~/dev/code.lengstorf.com/projects/test1.com, ~/dev/code.lengstorf.com/projects/test2.com etc

Would be great to clarify this starting points so i can then move onto the next stages with some confidence. 

D.

**Comment by jlengstorf** [comment]
Hey, @v3nt!

> 1. What folder should i be in to start with?

Any folder you want — I keep a `dev` folder for all of my code, but you can choose anywhere you like.

> 2. Why is ~/dev/code.lengstorf.com/ in a domain format? ie does it need to be or is ij just how you name folders?

No need for domain format — this is just how I name folders.

> 3. Will all of your web projects (even for different clients) go into this folder?
> 3b. so my local projects will be in ~/dev/code.lengstorf.com/projects/test1.com, ~/dev/code.lengstorf.com/projects/test2.com etc

All of my web projects go into `dev`. You can organize this however you want.

Good luck!
